# Generated by Django 4.2 on 2023-04-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='title',
        ),
    ]
