# Generated by Django 4.2 on 2023-04-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0002_remove_click_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='title',
            field=models.CharField(blank=True, default='count', max_length=100),
        ),
    ]
