# Generated by Django 4.2 on 2023-04-14 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0003_click_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='click',
            name='count',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='click',
            name='title',
            field=models.CharField(blank=True, default='count'),
        ),
    ]
